### ISSUE TITLE
negative active cases in plots

### ISSUE THREAD

**Issue by acekyken** [chschoenenberger/covid19_dashboard#1]
Thanks for the great dashboard! 
I noticed that the active cases in the new cases plot become negative at one point. 
![image](https://user-images.githubusercontent.com/45659079/76843349-f0c4a600-683b-11ea-8e35-a9bf78304810.png)
Chromium Version 80.0.3987.122 (Official Build) Arch Linux (64-bit)

**Comment by chschoenenberger** [comment]
Hi
Thanks for the feedback. Well I guess this is kind of expected. When there is an improvement, meaning there are more people recovered (or also if it worsens a lot with deaths), there will be more people recovered than newly confirmed meaning the number of active cases is negative. Or do you would you disagree?

**Comment by acekyken** [comment]
Hm. Then maybe my definition if active cases differs. I would think that active cases are all cases of people with covid19. That can be 0, but not negative. Is active cases in this plot the difference between confirmed cases and recovered cases per day?

**Comment by chschoenenberger** [comment]
No you are right, but this plot shows **new** active cases for each day and this can indeed be negative, can't it?
It is confirmed - recovered - deaths

**Comment by acekyken** [comment]
okay then, my bad!

**Comment by Lotterleben** [comment]
Just for the record, I found this confusing too– would you be open to changing the terminology on the legend or adding a short explanatory text? (will be happy to open a PR for that)

**Comment by chschoenenberger** [comment]
@Lotterleben sure thing, feel free to open a PR :)

**Comment by chschoenenberger** [comment]
![Unbenannt](https://user-images.githubusercontent.com/22217265/77012548-6f216500-696e-11ea-99af-c7b812f9781d.png)

Fixed 👍
