### ISSUE TITLE
More details for "Evolution since 100th case"

### ISSUE THREAD

**Issue by serl** [chschoenenberger/covid19_dashboard#10]
Hello,
I would find interesting if it was possible to add deaths and recoveries to the bottom right plot, as they are in the bottom left one (Cases per Country), i.e. dashed/dotted lines.

Anyway, thanks for your contribution to the knowledge! :)

**Comment by chschoenenberger** [comment]
Deceased cases are now available. Recoveries will not be provided as they are only estimated for most countries
