### ISSUE TITLE
Source Data issue resulting in faulty numbers in various parts of dashboard

### ISSUE THREAD

**Issue by syseliak** [chschoenenberger/covid19_dashboard#14]
Hi, currently US is showing more recovered than confirmed cases. 43847 confirmed cases, 44025 recovered

**Comment by chschoenenberger** [comment]
The folks from [Johns Hopkins](https://github.com/CSSEGISandData/COVID-19) have changed their data formats which causes some issues. I'll try to look into it asap.

**Comment by mvnaylor** [comment]
Same issue, but last night I noticed there were 0 recovered.

**Comment by chschoenenberger** [comment]
Johns Hopkins does not provide recovered cases for the US anymore. There's unfortunately not much I can do about that right now. The situation is unsatisfactory for me as well... I might change to a different data source over the weekend. These folks are scraping from various sources:
https://github.com/lazd/coronadatascraper

**Comment by chschoenenberger** [comment]
Again, all wrong numbers are resulting by changes in the source data by Johns Hopkins University. I will have a look at this as soon as I can:
Find more information on the source data issue here: https://github.com/CSSEGISandData/COVID-19/issues/1250

**Comment by ottacom** [comment]
Seems that something is changed now into https://github.com/CSSEGISandData/COVID-19/archive/master.zip
This file "time_series_19-covid-Recovered.csv" is missing
I'm getting data/time_series_19-covid-Recovered.csv' does not exist

**Comment by chschoenenberger** [comment]
Yeah I already saw that they changed something again... I'll look into it tonight

**Comment by ttaidapos** [comment]
Looks like they are reporting recovered cases, see below reported global cases the last 24hrs from time of this post.  This is Home Assistant using the JH API.  See Github here for API code.
https://github.com/home-assistant/core/tree/a3c55b5e96dc1045b85fba6a48aefb93a717031a/homeassistant/components/coronavirus

Additionally, they have updated reporting to more detailed at least for the US.  It now reports state and county, see 2nd image.  Note three additional "admin" panels on left pane where you're able to select State and then County respectively.

![image](https://user-images.githubusercontent.com/27898709/78040892-b1b34c00-7335-11ea-9c0b-a378bbca97d6.png)

![image](https://user-images.githubusercontent.com/27898709/78041076-eaebbc00-7335-11ea-8beb-e1f3c0a6da24.png)

**Comment by chschoenenberger** [comment]
I included the US state level data again and removed some weird behavior (cruise ship at 0, 0). I will not include counties as it is too much work for now.
Recovered cases are from data where available and estimated otherwise.

**Comment by ttaidapos** [comment]
> I included the US state level data again and removed some weird behavior (cruise ship at 0, 0). I will not include counties as it is too much work for now.
> Recovered cases are from data where available and estimated otherwise.

Thanks! How do you add state level sensors?

**Comment by chschoenenberger** [comment]
> 
> 
> > I included the US state level data again and removed some weird behavior (cruise ship at 0, 0). I will not include counties as it is too much work for now.
> > Recovered cases are from data where available and estimated otherwise.
> 
> Thanks! How do you add state level sensors?

What do you mean by "state level sensors"?

**Comment by ttaidapos** [comment]
> > > I included the US state level data again and removed some weird behavior (cruise ship at 0, 0). I will not include counties as it is too much work for now.
> > > Recovered cases are from data where available and estimated otherwise.
> > 
> > 
> > Thanks! How do you add state level sensors?
> 
> What do you mean by "state level sensors"?

Never mind mixed up to what I was responding to. Please ignore and thank you for all your hard work!
