### ISSUE TITLE
Cases on Diamond Princess are shown on Null Island

### ISSUE THREAD

**Issue by nnicksize** [chschoenenberger/covid19_dashboard#15]
The Cases on the cruise ship Diamond Princess are shown at 0°N 0°E.

The ship had been quarantined at Yokohama, Japan since February 4th ([source](https://www.princess.com/news/notices_and_advisories/notices/diamond-princess-update.html)).

**Comment by chschoenenberger** [comment]
The folks from Johns Hopkins have changed their data formats which causes some issues. I'll try to look into it asap.

**Comment by chschoenenberger** [comment]
This is also covered by this issue: https://github.com/chschoenenberger/covid19_dashboard/issues/14
