### ISSUE TITLE
Country table vs. map data differs

### ISSUE THREAD

**Issue by danielkec** [chschoenenberger/covid19_dashboard#16]
Country table vs. map data differs(confirmed is correct on map while deceased is correct in table)
![image](https://user-images.githubusercontent.com/1773630/77443313-46c0bd00-6deb-11ea-9df7-00a177c92870.png)

**Comment by chschoenenberger** [comment]
This is again the data issue from the source data. This is already referenced here: https://github.com/chschoenenberger/covid19_dashboard/issues/14
Johns Hopkins changed their data format and removed the recovered cases. This resulted in many issues that need to be tackled. 
I will close this issue
