### ISSUE TITLE
Errors on World population graphics

### ISSUE THREAD

**Issue by Neextor** [chschoenenberger/covid19_dashboard#23]
Hi Christoph;
Your work has been a great compagnion during the pandemic and I want to thank you for your contribution and how great has been as an info source for analisis. As of a great example of R for data analisis ;)
During those recent days I've noticed that the switching button on the plot area to shift between 100k (relative) and absolute data is giving errors due a missmatched on the table info showing 0 for all results. Maybe because of a World population information change or so.
In any case, thanks for your work!

**Comment by chschoenenberger** [comment]
Fixed it!
