### ISSUE TITLE
Data seems to be doubled

### ISSUE THREAD

**Issue by bmclachlan** [chschoenenberger/covid19_dashboard#24]
Starting probably more than 7 days ago, I've noticed that the data has all of a sudden doubled. For example, on June 30 the US total was 2,635,265 cases confirmed then on July 1, the US total jumped to 5,372,212. There now seems to be two entries for each country in the table data.

**Comment by guidosch** [comment]
I have the same issue for more than a week now.

**Comment by chschoenenberger** [comment]
Fixed
