### ISSUE TITLE
Duplicate data row in all countries

### ISSUE THREAD

**Issue by tnvuhai** [chschoenenberger/covid19_dashboard#25]
![image_2022-04-20_003027589](https://user-images.githubusercontent.com/77385477/164061667-c0d654b8-d07b-47b5-a59f-2ef2f9a3fb5d.png)
As you can see the data of all countries double themselves :D

**Comment by chschoenenberger** [comment]
Hi
This repository is not being maintained anymore. I will therefore not provide a fix.
Thanks for your understanding.
Christoph
