### ISSUE TITLE
Filter by Deceased cases (Feature request)

### ISSUE THREAD

**Issue by rhm-fyayc** [chschoenenberger/covid19_dashboard#5]
Hi, 

Would be possible to add also deceased cases to show the countries bubbles ?

Congrats for the work done, quite nice especially the plot section

**Comment by chschoenenberger** [comment]
It sure is! I will add it as soon as I get to it :) thanks for the input.

**Comment by chschoenenberger** [comment]
![deceased_map](https://user-images.githubusercontent.com/22217265/77251605-8eaadd00-6c4f-11ea-8a9a-8ecc15fc06da.png)
Done!
