### ISSUE TITLE
Ability to filter by location on overview (Feature request)

### ISSUE THREAD

**Issue by SeanBannister** [chschoenenberger/covid19_dashboard#6]
On the overview page it lists two tabs Country/Region and State/Province it'd be great if there was the ability to filter these lists to get a quick overview of a particular location.

Also thanks for your work on this!!!

**Comment by chschoenenberger** [comment]
![summaryTable_search](https://user-images.githubusercontent.com/22217265/77251939-b00cc880-6c51-11ea-8b8c-47cd609ba7bb.png)
Done
