### ISSUE TITLE
Auto hide Layer Selector

### ISSUE THREAD

**Issue by bockoblur** [chschoenenberger/covid19_dashboard#9]
Please consider implementing auto-hide for layer selection box.
It covers a significant portion of the map, especially on small screens.

Great work. Thanks.

**Comment by chschoenenberger** [comment]
![Screenshot_2020-03-23 COVID-19 Global Cases - Open Source Version](https://user-images.githubusercontent.com/22217265/77368317-40373480-6d5c-11ea-91c5-d520747c7d73.png)
Done 👍
